# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image
FROM node:20-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies (--ignore-scripts prevents the prepare script from running before source code is copied)
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Use a smaller Node.js image for the release
FROM node:20-slim AS release

# Set the working directory
WORKDIR /app

# Copy the build from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package-lock.json /app/

# Install production dependencies only
RUN npm ci --production --ignore-scripts

# Expose the necessary port
EXPOSE 3005

# Command to run the application
CMD ["node", "dist/enhanced-stdio-server.js"]
